# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: Aloha's Blog
subtitle: "不乱于心，不困于情。不畏将来，不念过往。"
description: '追寻罗素先生的脚步，渴望寻找到我想要的答案。'
keywords: "Blog, Computer Science, Medicine, Literature, Philosophy"
author: Qihuan Liu
language: cn
timezone: 'Asia/Shanghai'

# URL
## Set your site url here. For example, if you use GitHub Page, set url as 'https://username.github.io/project'
url: https://www.aloha.org.cn
permalink: :year/:month/:day/:title/
permalink_defaults:
pretty_urls:
  trailing_index: false # Set to false to remove trailing 'index.html' from permalinks
  trailing_html: false # Set to false to remove trailing '.html' from permalinks

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link:
  enable: true # Open external links in new tab
  field: site # Apply to the whole site
  exclude: ''
filename_case: 0
render_drafts: false
post_asset_folder: true
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: false
  tab_replace: ''
  wrap: true
  hljs: false
prismjs:
  enable: false
  preprocess: true
  line_number: true
  tab_replace: ''

# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ''
  per_page: 10
  order_by: -date

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Metadata elements
## https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta
meta_generator: false

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss
## updated_option supports 'mtime', 'date', 'empty'
updated_option: 'mtime'

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Include / Exclude file(s)
## include:/exclude: options only apply to the 'source/' folder
include: []
exclude: []
ignore: []

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: next

# Deployment
## Docs: https://hexo.io/docs/one-command-deployment
deploy:
  type: "git"
  repo: "git@github.com:alohaia/aloha.github.io"
  branch: "main"

# Search
## Docs: https://github.com/theme-next/hexo-generator-searchdb
search:
  path: search.xml
  field: all
  content: true
  format: html

## Docs: https://github.com/CHENXCHEN/hexo-renderer-markdown-it-plus
markdown_it_plus:
    highlight: true
    html: true
    xhtmlOut: true
    breaks: true
    langPrefix:
    linkify: true
    typographer:
    quotes: “”‘’
    pre_class: highlight
    plugins:
        - plugin:
            name: markdown-it-toc-and-anchor
            enable: true
            options:
                toc: true
                tocClassName: 'markdownIt-TOC'
                tocFirstLevel: 2
                tocLastLevel: 6
                tocCallback:
                anchorLink: true
                anchorLinkSymbol: ''
                anchorFirstLevel: 2
                anchorLastLevel: 6
                anchorLinkSpace: true
                anchorLinkSymbolClassName:
                anchorLinkBefore: true
                anchorClassName: 'markdownIt-Anchor'
                resetIds: true
        - plugin:   # https://github.com/linsir/markdown-it-task-checkbox
            name: markdown-it-task-checkbox
            enable: true
            options:
                disable: true   ## 默认
                divWrap: true
                divClass: checkbox
                idPrefix: cbx_
                ulClass: task-list
                liClass: task-list-item

# Markdown-it config
## Docs: https://github.com/celsomiranda/hexo-renderer-markdown-it/wiki
# markdown:
#     render:
#         html: true
#         xhtmlOut: false
#         breaks: true
#         linkify: true
#         typographer: true
#         quotes: '“”‘’'
#     enable_rules:
#     disable_rules:
#     plugins:
#         - markdown-it-abbr
#         - markdown-it-footnote
#         - markdown-it-ins
#         - markdown-it-sub
#         - markdown-it-sup
#     anchors:
#         level: 2
#         collisionSuffix: 'v'
#         permalink: true
#         permalinkClass: 'header-anchor'
#         permalinkSide: 'left'
#         permalinkSymbol: '¶'
#         case: 0
#         separator: ''

# RSS
feed:
    enable: true
    type:
        - atom
        - rss2
    path:
        - atom.xml
        - rss2.xml
    limit: 20
    hub:
    content:
    order_by: -date
    icon: icon.png
    content_limit:
    content_limit_delim: ' '
